# Generated by Django 2.2 on 2019-04-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
