# Generated by Django 2.2 on 2019-04-22 01:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0003_amazonuser_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='id',
        ),
        migrations.AddField(
            model_name='package',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='order_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_id',
            field=models.IntegerField(default=1),
        ),
    ]
