# Generated by Django 2.2 on 2019-04-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='package',
            name='trackingnumber',
            field=models.IntegerField(default=1),
        ),
    ]
