# Generated by Django 2.2 on 2019-04-22 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0007_auto_20190422_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False),
        ),
    ]
