# Generated by Django 2.2 on 2019-04-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0008_auto_20190422_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_of_ratings',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='totalscore',
            field=models.FloatField(default=0.0),
        ),
    ]
