# Generated by Django 2.2 on 2019-04-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0009_auto_20190423_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
