# Generated by Django 2.2 on 2019-04-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0010_package_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='num_of_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
