# Generated by Django 2.2 on 2019-04-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0011_auto_20190423_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonuser',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
