# Generated by Django 2.2 on 2019-04-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0012_amazonuser_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
