# Generated by Django 2.2 on 2019-04-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0013_package_returned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=200)),
                ('reward', models.BooleanField(default=False)),
            ],
        ),
    ]
