# Generated by Django 2.2 on 2019-04-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0014_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
