# Generated by Django 2.2 on 2019-04-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0015_feedback_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='reward',
            field=models.BooleanField(default=True),
        ),
    ]
